spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/learnredis
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  profiles:
     include: oauth

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug